name: Universal Convert

on:
  push:
    paths:
      - 'Backup.zip'
      - 'Backup.tachibk'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Python Dependencies
        run: |
          pip install protobuf==4.25.3

      - name: Compile Schema
        run: |
          # Compiles schema.proto into tachiyomi_pb2.py
          protoc --python_out=. schema.proto

      - name: Run Python Converter
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python main.py

      - name: Upload Converted Backup
        uses: actions/upload-artifact@v4
        with:
          name: converted_backup
          path: output/
          if-no-files-found: warn
          
